global:
  tracking_type: TRACKER
  tracking_rig: Colosseum
  experimental_design_factors:    
    feeding: [Starved, Control]
    sex: [Male, Female]
tracking_regions:
  T_0:
    experimental_factors: Starved, Female
    x_location_multiplier: 1
    y_location_multiplier: 1
  T_1:
    experimental_factors: Control, Male
    x_location_multiplier: 1
    y_location_multiplier: 1
  T_2:
    experimental_factors: Starved, Female
    x_location_multiplier: 1
    y_location_multiplier: 1
  T_3:
    experimental_factors: Control, Female
    x_location_multiplier: 1
    y_location_multiplier: 1
  T_4:
    experimental_factors: Starved, Female
    x_location_multiplier: 1
    y_location_multiplier: 1
  T_5:
    experimental_factors: Control, Male
    x_location_multiplier: 1
    y_location_multiplier: 1
  T_6:
    experimental_factors: Starved, Male
    x_location_multiplier: 1
    y_location_multiplier: 1
  T_7:
    experimental_factors: Control, Female
    x_location_multiplier: 1
    y_location_multiplier: 1
  T_8:
    experimental_factors: Starved, Male
    x_location_multiplier: 1
    y_location_multiplier: 1
  T_9:
    experimental_factors: Control, Female
    x_location_multiplier: 1
    y_location_multiplier: 1
  T_10:
    experimental_factors: Starved, Male
    x_location_multiplier: 1
    y_location_multiplier: 1
  T_11:
    experimental_factors: Control, Female
    x_location_multiplier: 1
    y_location_multiplier: 1
  T_12:
    experimental_factors: Control, Female
    x_location_multiplier: 1
    y_location_multiplier: 1
  T_13:
    experimental_factors: Starved, Female
    x_location_multiplier: 1
    y_location_multiplier: 1
  T_14:
    experimental_factors: Control, Female
    x_location_multiplier: 1
    y_location_multiplier: 1
  T_15:
    experimental_factors: Starved, Male
    x_location_multiplier: 1
    y_location_multiplier: 1
  T_16:
    experimental_factors: Control, Male
    x_location_multiplier: 1
    y_location_multiplier: 1
  T_17: 
    experimental_factors: Starved, Male
    x_location_multiplier: 1
    y_location_multiplier: 1
  T_18:
    experimental_factors: Control, Male
    x_location_multiplier: 1
    y_location_multiplier: 1
  T_19:
    experimental_factors: Starved, Female
    x_location_multiplier: 1
    y_location_multiplier: 1
  T_20:
    experimental_factors: Control, Male
    x_location_multiplier: 1
    y_location_multiplier: 1
  T_21:
    experimental_factors: Starved, Male
    x_location_multiplier: 1
    y_location_multiplier: 1
  T_22:
    experimental_factors: Control, Female
    x_location_multiplier: 1
    y_location_multiplier: 1
  T_23:
    experimental_factors: Starved, Female
    x_location_multiplier: 1
    y_location_multiplier: 1

# Counting regions are a dictionary with keys as the treatments and values as all the different regions in the datafile that correspond to each.
counting_regions:
  Light:
    alias: Light, LL, L
  NoLight:
    alias: NoLight, NL, N